version: '2.2'
services:
   web:
     build: .
     ports:
       - "24065:5000"
     cpus: 4
     mem_limit: 128M
     restart: on-failure
   redis:
     image: "redis:alpine"
     cpus: 4
     mem_limit: 128M
     restart: on-failure
